### PR TITLE
Create nidhi-nivedita.md

### PR DESCRIPTION
**Pull request by NidhiNivedita6**
Finding greater of two numbers

### CODE REVIEW

**Review by harshareddy794 — CHANGES_REQUESTED** [review]
Change the file from nidhi-nivedita.md to greatest number.cpp

**Comment by NidhiNivedita6** [comment]
I have made the required changes. Please review it.

**Review by harshareddy794 — CHANGES_REQUESTED** [review]
Good one @NidhiNivedita6 
Please create a new folder and add your code to it

**Comment by NidhiNivedita6** [comment]
Sir, I have deleted the old file and made a new folder named C in which I have added my code. Please review it.

**Comment by harshareddy794** [comment]
@NidhiNivedita6, For now, I'm closing this PR
Create a new folder in the CPP folder as the greatest number and then add your code in it and create a new PR. I'll merge it as soon as possible.

**Pull request closed without merging**
