### PR TITLE
Added matrix transpose

### PR DESCRIPTION
**Pull request by kumaryash18**
//added a program to transpose a matrix (2D array)

### CODE REVIEW

**Review by harshareddy794 — CHANGES_REQUESTED** [review]
@kumaryash18  can you create a new folder in the CPP folder as matrix transpose and add your code there instead of adding it to the CPP folder

**Comment by kumaryash18** [comment]
great, I will raise anther PR.

**Comment by kumaryash18** [comment]
#58

**Comment by harshareddy794** [comment]
I merged new PR so closing the old one  @kumaryash18

**Pull request closed without merging**
