### PR TITLE
Create fibonacci.cpp

### PR DESCRIPTION
**Pull request by parjanyaacoder**

### CODE REVIEW

**Comment by parjanyaacoder** [comment]
@harshareddy794 Please review. Thank you.

**Review by harshareddy794 — CHANGES_REQUESTED** [review]
Please create a folder for your code and add your code in it
btw nice work :grin:

**Comment by parjanyaacoder** [comment]
@harshareddy794 Done changes.

**Review by harshareddy794 — APPROVED** [review]
Thanks, @parjanyaacoder  for your contribution to open source community

**Pull request merged**
