### PR TITLE
Added some of the Data Structures in JS

### PR DESCRIPTION
**Pull request by palakyadav1807**
Added some of the Data Structures in JS

### CODE REVIEW

**Comment by palakyadav1807** [comment]
can u plz merge my pull request @harshareddy794

**Review by harshareddy794 — APPROVED** [review]
Awsome work @palakyadav1807 
Thanks for your contribution to open source community

**Comment by palakyadav1807** [comment]
Thankyou so much

**Comment by palakyadav1807** [comment]
Hello @harshareddy794 
Do you accept pull request with hacktober fest label??

**Pull request merged**
